import Slider from "@/components/slider"
import NavbarPremium from "@/components/navbarPremiun"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({children,}: {children: React.ReactNode}) {
  return <>
    <Slider
        title="E-migrAR"
        subtitle="Asesoría migratoria para una llegada segura y sin errores a Argentina"
        buttons={[
            { label: "Contactarse" },
                      
        ]}>
                              
        <NavbarPremium/>
    </Slider>
      
    {children}
  </>;
}
