import Navbar from "@/components/navbarLanding";
import Providers from "@/components/providers";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({children,}: {children: React.ReactNode}) {
  return <>{children}</>;
}
